### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by AlbertoFabio** [oneknlr/www.ongegrondehadith.nl#1]
Salaam Waheed,

Zeer boeiende website waar ik zeker inhoudelijk veel vragen over heb. Hopelijk kunnen we daar privé eens over hebben.

Technisch gezien ook heel mooi, alleen heb ik 1 dode link ontdekt bij 'truc 1'. Daar staat '' tegenspraak met de koran" als link, maar het linkt naar de pagina zelf. Ofwel is dat de bedoeling natuurlijk :-)

Bedankt voor de interessante info!

**Comment by oneknlr** [comment]
Gefix't.  Het staat je vrij je vragen direct aan mij te stellen (oneknlrATgmail), of beter nog op de koranisme google group:

https://groups.google.com/forum/#!forum/koranisme

Als je ze daar post kunnen wellicht anderen ook van jou vragen en de daaruit ontstaande discussie leren ;)

Dankjewel voor je feedback!

Salaam.
